### ISSUE TITLE
Inventario

### ISSUE THREAD

**Issue by SuperAlecs** [matcracker/InventoryExchanger#1]
Ciao potresti mettere un config per mettere che tutti i player abbiano l inventario uguale in certi mondi

**Comment by matcracker** [comment]
Si, si può fare. Appena sistemo un po' le cose inzio a fare quel config

**Comment by SuperAlecs** [comment]
Grande :D

**Comment by SuperAlecs** [comment]
potresti aggiungere anche che in certi mondi non possono droppare gli item?

**Comment by matcracker** [comment]
Ho aggiunto la possibilità di bloccare i drops in alcuni mondi

**Comment by SuperAlecs** [comment]
potresti aggiungere anche quando i player muoiono non droppano? Io ho cercato di farlo ma mi crasha xD, 
Ciao comunque :D

**Comment by matcracker** [comment]
Ciao! Si, aggiungerò tra qualche ora questa opzione!

**Comment by matcracker** [comment]
Aggiunto ed è già disponibile su PocketMine!
