### ISSUE TITLE
Per-world Inventory Issue

### ISSUE THREAD

**Issue by tytot** [matcracker/InventoryExchanger#2]
I'm running the latest build of InventoryExchanger (with per-world inventory), with the latest PocketMine build. I haven't made any changes to config.yml, yet when I change worlds, the inventory doesn't change, and I don't receive a message or anything. Can you try to help? Thanks.

**Comment by matcracker** [comment]
Oh, thanks for the issue, I didn't try the plugin the plugin after the remake and I knew only the inventory wasn't save. I try to check the code :)

**Comment by tytot** [comment]
Ok, thanks :)

**Comment by tytot** [comment]
btw you can close this, it suddenly started to work :+1:

**Comment by matcracker** [comment]
Mhmm... Strange.. xD
